exec_once:
 execs:
  Install Gitlab:
   name: Install Gitlab
   command: |
     #!/usr/bin/env bash
     sudo apt-get install -y curl openssh-server ca-certificates
     DEBIAN_FRONTEND=noninteractive apt-get install -y postfix
     curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
     sudo EXTERNAL_URL="http://gitlab.example.com" apt-get install -y gitlab-ee
     sudo gitlab-ctl reconfigure
